// examples/react/demo-app/src/App.tsx
import { useState } from 'react';
import DoctorTestComponent from './components/DoctorTestComponent';

const userRenderedContent = '<img src="invalid:" onerror="alert(1)">';

const App = () => {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className="container">
      <h1>Framework Doctor React Demo</h1>
      <p>A minimal React app with intentional issues for react-doctor testing.</p>

      <div className="example">
        <button type="button" onClick={() => setDarkMode(!darkMode)}>
          {darkMode ? '☀️ Light' : '🌙 Dark'}
        </button>
      </div>

      <hr />
      <h2>react-doctor test section (intentional issues)</h2>
      <div className="example">
        <DoctorTestComponent label="Test" />
        <div dangerouslySetInnerHTML={{ __html: userRenderedContent }} />
      </div>
    </div>
  );
};

export default App;

// examples/angular/demo-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { DoctorTestComponent } from './doctor-test.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [DoctorTestComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export default class AppComponent {
  darkMode = false;
  userRenderedContent = '<img src="invalid:" onerror="alert(1)">';

  toggleDarkMode(): void {
    this.darkMode = !this.darkMode;
  }
}

<div class="container">
  <h1>Framework Doctor Angular Demo</h1>
  <p>A minimal Angular app with intentional issues for angular-doctor testing.</p>

  <div class="example">
    <button type="button" (click)="toggleDarkMode()">
      {{ darkMode ? '☀️ Light' : '🌙 Dark' }}
    </button>
  </div>

  <hr />
  <h2>angular-doctor test section (intentional issues)</h2>
  <div class="example">
    <app-doctor-test label="Test" />
    <div [innerHTML]="userRenderedContent"></div>
  </div>
</div>
